### ISSUE TITLE
python main.py

### ISSUE THREAD

**Issue by lxy-mini** [shanmo/orcvio-kitti-python#2]

**Comment by lxy-mini** [comment]
(python36) zjut@zjut:~/2022_lxy/07/orcvio-kitti-python$ python main.py 
INFO:OpenGL.acceleratesupport:OpenGL_accelerate module loaded
INFO:OpenGL.arrays.arraydatatype:Using accelerated ArrayDatatype
Traceback (most recent call last):
  File "main.py", line 214, in <module>
    IP = sem.sem_img_proc.SemImageProcessor(dataset.cam, (dataset.cam.width, dataset.cam.height), kitti_end_index-1, PG, load_detection_flag)
  File "/home/zjut/2022_lxy/07/orcvio-kitti-python/sem/sem_img_proc.py", line 248, in __init__
    self.yolo_model = load_yolo_model(PG.yolo_path, PG.yolo_weights_path)
  File "/home/zjut/2022_lxy/07/orcvio-kitti-python/sem/sem_img_proc.py", line 20, in load_yolo_model
    yolo_model.load_weights(yolo_weights_path)
  File "/home/zjut/2022_lxy/07/orcvio-kitti-python/sem/../third_party/yolov3/darknet.py", line 299, in load_weights
    bn_biases = bn_biases.view_as(bn.bias.data)
RuntimeError: shape '[32]' is invalid for input of size 28_**

hello,When I run the code, I get an error.
and Can you tell me how your dataset is trained?

**Comment by shanmo** [comment]
- ~~please refer to https://github.com/moshanATucsd/orcvio_python_clean/issues/6~~
- I just realised the repo above is private, basically you need `git lfs pull` when downloading the pre-trained yolo model, the only modification I made to training is adding the dropout layer for keypoints, I did not modify the object detection model

**Comment by lxy-mini** [comment]
Hello, the URL _https://github.com/moshanATucsd/orcvio_python_clean/issues/6_ you gave is not accessible

**Comment by shanmo** [comment]
> Hello, the URL _https://github.com/moshanATucsd/orcvio_python_clean/issues/6_ you gave is not accessible

I extracted the solution `git lfs pull` in the comment above. Please ignore that url.
