### ISSUE TITLE
my own dataset

### ISSUE THREAD

**Issue by lxy-mini** [shanmo/orcvio-kitti-python#3]
I need to use my dataset now, what do I need to pay attention to？

**Comment by lxy-mini** [comment]
hello

**Comment by shanmo** [comment]
I am not sure what kind of data you have but in general the measurements should be similar to those in euroc dataset, ie time synchronised, have sufficient fps, calibrated, etc. You can refer to this 

如何在kitti raw data上跑起vins-mono - 邱笑晨的文章 - 知乎
https://zhuanlan.zhihu.com/p/75672946
